version: '3.1'

services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes: 
      - mysql_vol:/var/lib/mysql
    networks:
      - ghost-net

  ghost:
    depends_on: 
      - mysql
    image: ghost:5-alpine
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: mysql
      database__connection__user: ${DB_USER}
      database__connection__password: ${DB_PASSWORD}
      database__connection__database: ${DB_NAME}
      url: https://${LOCAL_DOMAIN}
    networks:
      - ghost-net

  proxy:
    depends_on:
      - ghost
    image: nginx:1.25-alpine
    container_name: proxy
    restart: unless-stopped
    env_file: .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs
      - ./proxy-config/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - ghost-net

volumes:
  ghost_vol:
  mysql_vol:

networks:
  ghost-net:
    driver: bridge
